apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookpublish
  labels:
    app: bookpublish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookpublish
  template:
    metadata:
      labels:
        app: bookpublish
    spec:
      containers:
        - name: bookpublish
          image: "username/bookpublish:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
