apiVersion: apps/v1
kind: Deployment
metadata:
  name: genstory
  labels:
    app: genstory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genstory
  template:
    metadata:
      labels:
        app: genstory
    spec:
      containers:
        - name: genstory
          image: "username/genstory:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
