server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
#<<< API Gateway / Routes
      routes:
        - id: bookpublish
          uri: http://localhost:8082
          predicates:
            - Path=/bookPublishes/**, 
        - id: bookpurchase
          uri: http://localhost:8083
          predicates:
            - Path=/bookPurchases/**, 
        - id: member
          uri: http://localhost:8084
          predicates:
            - Path=/members/**, 
        - id: review
          uri: http://localhost:8085
          predicates:
            - Path=/bookReviews/**, 
        - id: genstory
          uri: http://localhost:8086
          predicates:
            - Path=/genStories/**, 
        - id: genimage
          uri: http://localhost:8087
          predicates:
            - Path=/genImages/**, 
        - id: pay
          uri: http://localhost:8088
          predicates:
            - Path=/paymenthistories/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
#>>> API Gateway / Routes
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: bookpublish
          uri: http://bookpublish:8080
          predicates:
            - Path=/bookPublishes/**, 
        - id: bookpurchase
          uri: http://bookpurchase:8080
          predicates:
            - Path=/bookPurchases/**, 
        - id: member
          uri: http://member:8080
          predicates:
            - Path=/members/**, 
        - id: review
          uri: http://review:8080
          predicates:
            - Path=/bookReviews/**, 
        - id: genstory
          uri: http://genstory:8080
          predicates:
            - Path=/genStories/**, 
        - id: genimage
          uri: http://genimage:8080
          predicates:
            - Path=/genImages/**, 
        - id: pay
          uri: http://pay:8080
          predicates:
            - Path=/paymenthistories/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
