---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookpublish
  labels:
    app: bookpublish
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookpublish
  template:
    metadata:
      labels:
        app: bookpublish
    spec:
      containers:
        - name: bookpublish
          image: username/bookpublish:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookpurchase
  labels:
    app: bookpurchase
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookpurchase
  template:
    metadata:
      labels:
        app: bookpurchase
    spec:
      containers:
        - name: bookpurchase
          image: username/bookpurchase:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: member
  labels:
    app: member
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member
  template:
    metadata:
      labels:
        app: member
    spec:
      containers:
        - name: member
          image: username/member:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: review
  labels:
    app: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review
  template:
    metadata:
      labels:
        app: review
    spec:
      containers:
        - name: review
          image: username/review:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genstory
  labels:
    app: genstory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genstory
  template:
    metadata:
      labels:
        app: genstory
    spec:
      containers:
        - name: genstory
          image: username/genstory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: genimage
  labels:
    app: genimage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genimage
  template:
    metadata:
      labels:
        app: genimage
    spec:
      containers:
        - name: genimage
          image: username/genimage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pay
  labels:
    app: pay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pay
  template:
    metadata:
      labels:
        app: pay
    spec:
      containers:
        - name: pay
          image: username/pay:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: bookpublish
  labels:
    app: bookpublish
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookpublish


---


apiVersion: v1
kind: Service
metadata:
  name: bookpurchase
  labels:
    app: bookpurchase
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: bookpurchase


---


apiVersion: v1
kind: Service
metadata:
  name: member
  labels:
    app: member
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: member


---


apiVersion: v1
kind: Service
metadata:
  name: review
  labels:
    app: review
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: review


---


apiVersion: v1
kind: Service
metadata:
  name: genstory
  labels:
    app: genstory
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: genstory


---


apiVersion: v1
kind: Service
metadata:
  name: genimage
  labels:
    app: genimage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: genimage


---


apiVersion: v1
kind: Service
metadata:
  name: pay
  labels:
    app: pay
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: pay

